### PR TITLE
Handle pre-CLIENT_PROTOCOL_41 errors

### LINKED ISSUE #68: Consider error messages starting with 0x48
I have hit 2 MySql error messages starting with the byte 0x48 instead of 0x23.

These exceptions are:

- 1130 Host 'x.x.x.x' is not allowed to connect to this MySql Server
- 1203 Too Many Connections

Presently the exception comes across as:

    Unhandled Exception: System.FormatException: Expected to read 0x23 but got 0x48
       at MySql.Data.ByteArrayReader.ReadByte(Byte value)

I'm working up a fix to check for 0x23 and 0x48 that will print:

    Unhandled Exception: MySql.Data.MySqlClient.MySqlException: '172.17.0.1' is not allowed to connect to this MySQL server
       at MySql.Data.Serialization.PayloadData.ThrowIfError()

### PR DESCRIPTION
**Pull request by caleblloyd**
Fixes #68

### CODE REVIEW

File: src/MySqlConnector/ByteArrayReader.cs [hunk 1]
```diff
@@ -40,10 +41,20 @@ public byte ReadByte()
 			return m_buffer[m_offset++];
 		}
 
-		public void ReadByte(byte value)
+		public void ReadByte(params byte[] possibleValues)
```
Comment (bgrainger) [inline src/MySqlConnector/ByteArrayReader.cs]: This will cause an array allocation for every call to this methd.

File: src/MySqlConnector/ByteArrayReader.cs [hunk 2]
```diff
@@ -40,10 +41,20 @@ public byte ReadByte()
...
 		{
-			if (ReadByte() != value)
-				throw new FormatException("Expected to read 0x{0:X2} but got 0x{1:X2}".FormatInvariant(value, m_buffer[m_offset - 1]));
+			var readByte = ReadByte();
+			if (possibleValues.Any(value => readByte == value))
```
Comment (bgrainger) [inline src/MySqlConnector/ByteArrayReader.cs]: This will allocate a lambda; a simple `foreach` might be better.

File: src/MySqlConnector/Serialization/ErrorPayload.cs [hunk 3]
```diff
@@ -21,7 +21,7 @@ public static ErrorPayload Create(PayloadData payload)
 			reader.ReadByte(Signature);
 
 			var errorCode = reader.ReadUInt16();
-			reader.ReadByte(0x23);
+			reader.ReadByte(0x23, 0x48);
```
Comment (bgrainger) [inline src/MySqlConnector/Serialization/ErrorPayload.cs]: I think the real problem here is that I hard-coded `0x23`. The [documentation](https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html) just defines it as "# marker of the SQL State". I'm not sure where I got the value `0x23`; maybe I just observed that in practice and assumed it was a constant?

It does not appear to be a constant :smile: and the documentation doesn't specify the set of allowed values, so I would revert the changes to `ReadByte` and just change this line to `var sqlStateMarker = reader.ReadByte();` (and discard the value).

Comment (bgrainger) [inline src/MySqlConnector/Serialization/ErrorPayload.cs]: `0x23` is `#`, so I guess I interpreted "# marker of the SQL State" as meaning it was the constant `'#'`.

Still not sure what `0x48` (== `'H'`) means, but it must be an acceptable state marker. Since we're not doing anything with that value, it seems safe to ignore it if the rest of the packet looks right.

**Comment by caleblloyd** [comment]
It looks like MariaDB's java driver holds all of the answers.  It's "old style" and "new style" error messages: https://github.com/MariaDB/mariadb-connector-j/blob/master/src/main/java/org/mariadb/jdbc/internal/packet/result/ErrorPacket.java#L70

I'll code it up according to their logic

**Comment by bgrainger** [comment]
Oh, it's a pre-`CLIENT_PROTOCOL_41` error? That would make sense. Until we've sent back the `HandshakeResponse41Packet`, the server doesn't know if we support the new protocol.

**Comment by bgrainger** [comment]
A simple approach may be to call `reader.ReadByteString` to read everything after the error code (as a string) then check if `message[0] == '#'` and perform the necessary Substring calls.

**Comment by caleblloyd** [comment]
Updated PR with new changes
